site_name: Apollo Docs
repo_url: https://github.com/Exotify/exocom.github.io
repo_name: Apollo

markdown_extensions:
  - toc:
     permalink: true
     title: On this page
  
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  - attr_list
  - md_in_html

  - admonition
  - pymdownx.details
  
extra_css:
  - css/extra.css

nav:
  - Home:
    - index.md
  - Getting Started:
    - started.md
  - Tutorial:
    - tutorial/guns.md
    - tutorial/basic.md
    - tutorial/advanced.md
  - Support:
    - support.md

theme:
  name: material
  logo: img/LogoText.png
  favicon: img/LogoText.png
  features:
    - navigation.tabs
    - navigation.footer
    - navigation.indexes

    - navigation.path

    - toc.integrate 

    - navigation.top
    
  palette:
    primary: custom
    scheme: slate
    accent: orange